/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tela;

import javax.swing.JOptionPane;

/**
 *
 * @author Maykon Rodrigues
 */
public class TelaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form TelaPrincipal
     */
    public TelaPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem4 = new javax.swing.JMenuItem();
        jPanel1 = new javax.swing.JPanel();
        Desktop = new javax.swing.JDesktopPane();
        Menu = new javax.swing.JMenuBar();
        jMnArquivo = new javax.swing.JMenu();
        jMnSair = new javax.swing.JMenuItem();
        jMnCadastro = new javax.swing.JMenu();
        jMnClientes = new javax.swing.JMenuItem();
        jMnFornecedores = new javax.swing.JMenuItem();
        jMnUsuarios = new javax.swing.JMenuItem();
        jMnRelatorios = new javax.swing.JMenu();
        jMnOpcoes = new javax.swing.JMenu();
        jMnAjuda = new javax.swing.JMenu();
        jMnSobre = new javax.swing.JMenuItem();

        jMenuItem4.setText("jMenuItem4");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sistema SGC");
        setResizable(false);

        Desktop.setBackground(new java.awt.Color(204, 204, 204));

        javax.swing.GroupLayout DesktopLayout = new javax.swing.GroupLayout(Desktop);
        Desktop.setLayout(DesktopLayout);
        DesktopLayout.setHorizontalGroup(
            DesktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 753, Short.MAX_VALUE)
        );
        DesktopLayout.setVerticalGroup(
            DesktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 430, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Desktop)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Desktop)
        );

        jMnArquivo.setText("Arquivo");

        jMnSair.setText("Sair");
        jMnSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMnSairActionPerformed(evt);
            }
        });
        jMnArquivo.add(jMnSair);

        Menu.add(jMnArquivo);

        jMnCadastro.setText("Cadastro");

        jMnClientes.setText("Clientes");
        jMnCadastro.add(jMnClientes);

        jMnFornecedores.setText("Fornecedores");
        jMnFornecedores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMnFornecedoresActionPerformed(evt);
            }
        });
        jMnCadastro.add(jMnFornecedores);

        jMnUsuarios.setText("Usuários");
        jMnUsuarios.setEnabled(false);
        jMnUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMnUsuariosActionPerformed(evt);
            }
        });
        jMnCadastro.add(jMnUsuarios);

        Menu.add(jMnCadastro);

        jMnRelatorios.setText("Relatórios");
        Menu.add(jMnRelatorios);

        jMnOpcoes.setText("Opções");
        Menu.add(jMnOpcoes);

        jMnAjuda.setText("Ajuda");

        jMnSobre.setText("Sobre");
        jMnSobre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMnSobreActionPerformed(evt);
            }
        });
        jMnAjuda.add(jMnSobre);

        Menu.add(jMnAjuda);

        setJMenuBar(Menu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(769, 490));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jMnFornecedoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMnFornecedoresActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMnFornecedoresActionPerformed

    private void jMnUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMnUsuariosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMnUsuariosActionPerformed

    private void jMnSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMnSairActionPerformed
        int sair = JOptionPane.showConfirmDialog(null, "Tem certeza que deseja sair?", "Atenção", JOptionPane.YES_NO_OPTION);
        if (sair == JOptionPane.YES_OPTION) {
            System.exit(0);
        }
    }//GEN-LAST:event_jMnSairActionPerformed

    private void jMnSobreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMnSobreActionPerformed
        TelaSobre sobre = new TelaSobre();
        sobre.setVisible(true);
    }//GEN-LAST:event_jMnSobreActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane Desktop;
    private javax.swing.JMenuBar Menu;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenu jMnAjuda;
    private javax.swing.JMenu jMnArquivo;
    private javax.swing.JMenu jMnCadastro;
    private javax.swing.JMenuItem jMnClientes;
    private javax.swing.JMenuItem jMnFornecedores;
    private javax.swing.JMenu jMnOpcoes;
    private javax.swing.JMenu jMnRelatorios;
    private javax.swing.JMenuItem jMnSair;
    private javax.swing.JMenuItem jMnSobre;
    public static javax.swing.JMenuItem jMnUsuarios;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
